### ISSUE TITLE
don't want to get sued

### ISSUE THREAD

**Issue by jonathan-chin** [jonathan-chin/mec-ttp-2021-winter-assignment-1-sample#1]
we can't use the term lightsaber in our story. need to change it to something else.

**Comment by mec-cuny2x-advising** [comment]
Maybe use "laser-sword"?

**Comment by ElvisRodriguez** [comment]
Laser-sword sounds great, @rtaverna may I take up this issue?

**Comment by ElvisRodriguez** [comment]
Resolved name issue: resolved.
